spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/medi?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:medi}
    password: ${DB_PASSWORD:medi}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:myStrongRedisPassword}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
