package com.medi.domain.category;

public enum CategoryUsageType {
	HOSPITAL_DOCTOR_SUBJECT,
	HOSPITAL_REVIEW_SURGERY,
	HOSPITAL_REVIEW_TREATMENT,
	HOSPITAL_EVENT_SURGERY,
	HOSPITAL_EVENT_TREATMENT,
	HOSPITAL_VIDEO_CATEGORY,
	HOSPITAL_EVENT_AD_SURGERY,
	HOSPITAL_EVENT_AD_TREATMENT
}
