-- 병원 의료 카테고리 기준 트리
-- 구조 변경은 별도 migration으로 관리하고 이 파일은 초기 기준 데이터만 담당한다.

CREATE TEMPORARY TABLE category_seed (
    domain VARCHAR(40) NOT NULL,
    parent_code VARCHAR(80) NULL,
    depth TINYINT NOT NULL,
    group_code VARCHAR(30) NULL,
    name VARCHAR(120) NOT NULL,
    code VARCHAR(80) NOT NULL,
    full_path VARCHAR(255) NOT NULL,
    sort_order INT NOT NULL,
    PRIMARY KEY (domain, code)
);

INSERT INTO category_seed (domain, parent_code, depth, group_code, name, code, full_path, sort_order) VALUES
('HOSPITAL_MEDICAL', NULL, 1, 'SURGERY', '눈', 'HS_EYE', '눈', 1),
('HOSPITAL_MEDICAL', 'HS_EYE', 2, 'SURGERY', '쌍꺼풀', 'HS_EYE_DOUBLE', '눈 > 쌍꺼풀', 1),
('HOSPITAL_MEDICAL', 'HS_EYE_DOUBLE', 3, 'SURGERY', '자연유착', 'HS_EYE_DOUBLE_NATURAL', '눈 > 쌍꺼풀 > 자연유착', 1),
('HOSPITAL_MEDICAL', 'HS_EYE_DOUBLE', 3, 'SURGERY', '매몰', 'HS_EYE_DOUBLE_BURIED', '눈 > 쌍꺼풀 > 매몰', 2),
('HOSPITAL_MEDICAL', 'HS_EYE_DOUBLE', 3, 'SURGERY', '절개', 'HS_EYE_DOUBLE_INCISION', '눈 > 쌍꺼풀 > 절개', 3),
('HOSPITAL_MEDICAL', 'HS_EYE_DOUBLE', 3, 'SURGERY', '부분절개', 'HS_EYE_DOUBLE_PARTIAL_INCISION', '눈 > 쌍꺼풀 > 부분절개', 4),
('HOSPITAL_MEDICAL', 'HS_EYE', 2, 'SURGERY', '트임', 'HS_EYE_CANTHOPLASTY', '눈 > 트임', 2),
('HOSPITAL_MEDICAL', 'HS_EYE_CANTHOPLASTY', 3, 'SURGERY', '앞트임', 'HS_EYE_EPICANTHOPLASTY', '눈 > 트임 > 앞트임', 1),
('HOSPITAL_MEDICAL', 'HS_EYE_CANTHOPLASTY', 3, 'SURGERY', '뒤트임', 'HS_EYE_LATERAL_CANTHOPLASTY', '눈 > 트임 > 뒤트임', 2),
('HOSPITAL_MEDICAL', 'HS_EYE_CANTHOPLASTY', 3, 'SURGERY', '윗트임', 'HS_EYE_UPPER_CANTHOPLASTY', '눈 > 트임 > 윗트임', 3),
('HOSPITAL_MEDICAL', 'HS_EYE_CANTHOPLASTY', 3, 'SURGERY', '밑트임', 'HS_EYE_LOWER_CANTHOPLASTY', '눈 > 트임 > 밑트임', 4),
('HOSPITAL_MEDICAL', 'HS_EYE_CANTHOPLASTY', 3, 'SURGERY', '트임복원', 'HS_EYE_CANTHOPLASTY_RESTORE', '눈 > 트임 > 트임복원', 5),
('HOSPITAL_MEDICAL', 'HS_EYE', 2, 'SURGERY', '눈매교정', 'HS_EYE_PTOSIS', '눈 > 눈매교정', 3),
('HOSPITAL_MEDICAL', 'HS_EYE_PTOSIS', 3, 'SURGERY', '절개', 'HS_EYE_PTOSIS_INCISION', '눈 > 눈매교정 > 절개', 1),
('HOSPITAL_MEDICAL', 'HS_EYE_PTOSIS', 3, 'SURGERY', '비절개', 'HS_EYE_PTOSIS_NON_INCISION', '눈 > 눈매교정 > 비절개', 2),
('HOSPITAL_MEDICAL', 'HS_EYE', 2, 'SURGERY', '눈거상', 'HS_EYE_LIFT', '눈 > 눈거상', 4),
('HOSPITAL_MEDICAL', 'HS_EYE_LIFT', 3, 'SURGERY', '상안검', 'HS_EYE_LIFT_UPPER_BLEPHAROPLASTY', '눈 > 눈거상 > 상안검', 1),
('HOSPITAL_MEDICAL', 'HS_EYE_LIFT', 3, 'SURGERY', '하안검', 'HS_EYE_LIFT_LOWER_BLEPHAROPLASTY', '눈 > 눈거상 > 하안검', 2),
('HOSPITAL_MEDICAL', 'HS_EYE_LIFT', 3, 'SURGERY', '눈썹거상', 'HS_EYE_LIFT_BROW', '눈 > 눈거상 > 눈썹거상', 3),
('HOSPITAL_MEDICAL', 'HS_EYE', 2, 'SURGERY', '눈지방', 'HS_EYE_FAT', '눈 > 눈지방', 5),
('HOSPITAL_MEDICAL', 'HS_EYE_FAT', 3, 'SURGERY', '눈밑지방재배치', 'HS_EYE_FAT_UNDER_EYE_REPOSITION', '눈 > 눈지방 > 눈밑지방재배치', 1),
('HOSPITAL_MEDICAL', 'HS_EYE_FAT', 3, 'SURGERY', '눈꺼풀지방제거', 'HS_EYE_FAT_EYELID_REMOVAL', '눈 > 눈지방 > 눈꺼풀지방제거', 2),
('HOSPITAL_MEDICAL', 'HS_EYE', 2, 'SURGERY', '눈재수술', 'HS_EYE_REVISION', '눈 > 눈재수술', 6),
('HOSPITAL_MEDICAL', 'HS_EYE_REVISION', 3, 'SURGERY', '쌍꺼풀', 'HS_EYE_REVISION_DOUBLE', '눈 > 눈재수술 > 쌍꺼풀', 1),
('HOSPITAL_MEDICAL', 'HS_EYE_REVISION', 3, 'SURGERY', '트임', 'HS_EYE_REVISION_CANTHOPLASTY', '눈 > 눈재수술 > 트임', 2),
('HOSPITAL_MEDICAL', 'HS_EYE_REVISION', 3, 'SURGERY', '눈매교정', 'HS_EYE_REVISION_PTOSIS', '눈 > 눈재수술 > 눈매교정', 3),
('HOSPITAL_MEDICAL', 'HS_EYE_REVISION', 3, 'SURGERY', '눈거상', 'HS_EYE_REVISION_LIFT', '눈 > 눈재수술 > 눈거상', 4),
('HOSPITAL_MEDICAL', 'HS_EYE_REVISION', 3, 'SURGERY', '기타', 'HS_EYE_REVISION_OTHER', '눈 > 눈재수술 > 기타', 5),
('HOSPITAL_MEDICAL', NULL, 1, 'SURGERY', '코', 'HS_NOSE', '코', 2),
('HOSPITAL_MEDICAL', 'HS_NOSE', 2, 'SURGERY', '첫코', 'HS_NOSE_FIRST', '코 > 첫코', 1),
('HOSPITAL_MEDICAL', 'HS_NOSE_FIRST', 3, 'SURGERY', '콧대 + 코끝', 'HS_NOSE_FIRST_BRIDGE_TIP', '코 > 첫코 > 콧대 + 코끝', 1),
('HOSPITAL_MEDICAL', 'HS_NOSE_FIRST', 3, 'SURGERY', '절골술', 'HS_NOSE_FIRST_OSTEOTOMY', '코 > 첫코 > 절골술', 2),
('HOSPITAL_MEDICAL', 'HS_NOSE_FIRST', 3, 'SURGERY', '무보형물', 'HS_NOSE_FIRST_NO_IMPLANT', '코 > 첫코 > 무보형물', 3),
('HOSPITAL_MEDICAL', 'HS_NOSE', 2, 'SURGERY', '콧대', 'HS_NOSE_BRIDGE', '코 > 콧대', 2),
('HOSPITAL_MEDICAL', 'HS_NOSE_BRIDGE', 3, 'SURGERY', '콧대(자가조직)', 'HS_NOSE_BRIDGE_AUTOGRAFT', '코 > 콧대 > 콧대(자가조직)', 1),
('HOSPITAL_MEDICAL', 'HS_NOSE_BRIDGE', 3, 'SURGERY', '콧대(보형물)', 'HS_NOSE_BRIDGE_IMPLANT', '코 > 콧대 > 콧대(보형물)', 2),
('HOSPITAL_MEDICAL', 'HS_NOSE_BRIDGE', 3, 'SURGERY', '코절골술', 'HS_NOSE_BRIDGE_OSTEOTOMY', '코 > 콧대 > 코절골술', 3),
('HOSPITAL_MEDICAL', 'HS_NOSE', 2, 'SURGERY', '코끝', 'HS_NOSE_TIP', '코 > 코끝', 3),
('HOSPITAL_MEDICAL', 'HS_NOSE_TIP', 3, 'SURGERY', '코끝', 'HS_NOSE_TIP_BASIC', '코 > 코끝 > 코끝', 1),
('HOSPITAL_MEDICAL', 'HS_NOSE_TIP', 3, 'SURGERY', '연골묶기', 'HS_NOSE_TIP_CARTILAGE_BINDING', '코 > 코끝 > 연골묶기', 2),
('HOSPITAL_MEDICAL', 'HS_NOSE_TIP', 3, 'SURGERY', '비주(코기둥)', 'HS_NOSE_TIP_COLUMELLA', '코 > 코끝 > 비주(코기둥)', 3),
('HOSPITAL_MEDICAL', 'HS_NOSE_TIP', 3, 'SURGERY', '인중', 'HS_NOSE_TIP_PHILTRUM', '코 > 코끝 > 인중', 4),
('HOSPITAL_MEDICAL', 'HS_NOSE', 2, 'SURGERY', '기능코', 'HS_NOSE_FUNCTIONAL', '코 > 기능코', 4),
('HOSPITAL_MEDICAL', 'HS_NOSE_FUNCTIONAL', 3, 'SURGERY', '비염', 'HS_NOSE_FUNCTIONAL_RHINITIS', '코 > 기능코 > 비염', 1),
('HOSPITAL_MEDICAL', 'HS_NOSE_FUNCTIONAL', 3, 'SURGERY', '비중격만곡', 'HS_NOSE_FUNCTIONAL_SEPTUM', '코 > 기능코 > 비중격만곡', 2),
('HOSPITAL_MEDICAL', 'HS_NOSE_FUNCTIONAL', 3, 'SURGERY', '기타(비밸브, 축농증)', 'HS_NOSE_FUNCTIONAL_OTHER', '코 > 기능코 > 기타(비밸브, 축농증)', 3),
('HOSPITAL_MEDICAL', 'HS_NOSE', 2, 'SURGERY', '콧볼', 'HS_NOSE_ALAR', '코 > 콧볼', 5),
('HOSPITAL_MEDICAL', 'HS_NOSE_ALAR', 3, 'SURGERY', '비절개', 'HS_NOSE_ALAR_NON_INCISION', '코 > 콧볼 > 비절개', 1),
('HOSPITAL_MEDICAL', 'HS_NOSE_ALAR', 3, 'SURGERY', '내외측절개', 'HS_NOSE_ALAR_INCISION', '코 > 콧볼 > 내외측절개', 2),
('HOSPITAL_MEDICAL', 'HS_NOSE', 2, 'SURGERY', '코재수술', 'HS_NOSE_REVISION', '코 > 코재수술', 6),
('HOSPITAL_MEDICAL', 'HS_NOSE_REVISION', 3, 'SURGERY', '콧대 + 코끝', 'HS_NOSE_REVISION_BRIDGE_TIP', '코 > 코재수술 > 콧대 + 코끝', 1),
('HOSPITAL_MEDICAL', 'HS_NOSE_REVISION', 3, 'SURGERY', '콧대', 'HS_NOSE_REVISION_BRIDGE', '코 > 코재수술 > 콧대', 2),
('HOSPITAL_MEDICAL', 'HS_NOSE_REVISION', 3, 'SURGERY', '코끝', 'HS_NOSE_REVISION_TIP', '코 > 코재수술 > 코끝', 3),
('HOSPITAL_MEDICAL', 'HS_NOSE_REVISION', 3, 'SURGERY', '기능코', 'HS_NOSE_REVISION_FUNCTIONAL', '코 > 코재수술 > 기능코', 4),
('HOSPITAL_MEDICAL', 'HS_NOSE_REVISION', 3, 'SURGERY', '콧볼', 'HS_NOSE_REVISION_ALAR', '코 > 코재수술 > 콧볼', 5),
('HOSPITAL_MEDICAL', 'HS_NOSE_REVISION', 3, 'SURGERY', '기타', 'HS_NOSE_REVISION_OTHER', '코 > 코재수술 > 기타', 6),
('HOSPITAL_MEDICAL', NULL, 1, 'SURGERY', '지방흡입 / 이식', 'HS_BODY', '지방흡입 / 이식', 3),
('HOSPITAL_MEDICAL', 'HS_BODY', 2, 'SURGERY', '바디지방흡입', 'HS_BODY_LIPOSUCTION', '지방흡입 / 이식 > 바디지방흡입', 1),
('HOSPITAL_MEDICAL', 'HS_BODY_LIPOSUCTION', 3, 'SURGERY', '복부', 'HS_BODY_LIPOSUCTION_ABDOMEN', '지방흡입 / 이식 > 바디지방흡입 > 복부', 1),
('HOSPITAL_MEDICAL', 'HS_BODY_LIPOSUCTION', 3, 'SURGERY', '팔', 'HS_BODY_LIPOSUCTION_ARM', '지방흡입 / 이식 > 바디지방흡입 > 팔', 2),
('HOSPITAL_MEDICAL', 'HS_BODY_LIPOSUCTION', 3, 'SURGERY', '허벅지', 'HS_BODY_LIPOSUCTION_THIGH', '지방흡입 / 이식 > 바디지방흡입 > 허벅지', 3),
('HOSPITAL_MEDICAL', 'HS_BODY_LIPOSUCTION', 3, 'SURGERY', '엉덩이 / 골반', 'HS_BODY_LIPOSUCTION_HIP_PELVIS', '지방흡입 / 이식 > 바디지방흡입 > 엉덩이 / 골반', 4),
('HOSPITAL_MEDICAL', 'HS_BODY_LIPOSUCTION', 3, 'SURGERY', '기타(무릎 / 종아리 / 발목 / 등 / 승모근 / 쇄골 등)', 'HS_BODY_LIPOSUCTION_OTHER', '지방흡입 / 이식 > 바디지방흡입 > 기타(무릎 / 종아리 / 발목 / 등 / 승모근 / 쇄골 등)', 5),
('HOSPITAL_MEDICAL', 'HS_BODY', 2, 'SURGERY', '바디지방흡입 재수술', 'HS_BODY_LIPOSUCTION_REVISION', '지방흡입 / 이식 > 바디지방흡입 재수술', 2),
('HOSPITAL_MEDICAL', 'HS_BODY_LIPOSUCTION_REVISION', 3, 'SURGERY', '복부', 'HS_BODY_LIPOSUCTION_REVISION_ABDOMEN', '지방흡입 / 이식 > 바디지방흡입 재수술 > 복부', 1),
('HOSPITAL_MEDICAL', 'HS_BODY_LIPOSUCTION_REVISION', 3, 'SURGERY', '팔', 'HS_BODY_LIPOSUCTION_REVISION_ARM', '지방흡입 / 이식 > 바디지방흡입 재수술 > 팔', 2),
('HOSPITAL_MEDICAL', 'HS_BODY_LIPOSUCTION_REVISION', 3, 'SURGERY', '허벅지', 'HS_BODY_LIPOSUCTION_REVISION_THIGH', '지방흡입 / 이식 > 바디지방흡입 재수술 > 허벅지', 3),
('HOSPITAL_MEDICAL', 'HS_BODY_LIPOSUCTION_REVISION', 3, 'SURGERY', '엉덩이/골반', 'HS_BODY_LIPOSUCTION_REVISION_HIP_PELVIS', '지방흡입 / 이식 > 바디지방흡입 재수술 > 엉덩이/골반', 4),
('HOSPITAL_MEDICAL', 'HS_BODY_LIPOSUCTION_REVISION', 3, 'SURGERY', '기타', 'HS_BODY_LIPOSUCTION_REVISION_OTHER', '지방흡입 / 이식 > 바디지방흡입 재수술 > 기타', 5),
('HOSPITAL_MEDICAL', 'HS_BODY', 2, 'SURGERY', '얼굴지방흡입', 'HS_FACE_LIPOSUCTION', '지방흡입 / 이식 > 얼굴지방흡입', 3),
('HOSPITAL_MEDICAL', 'HS_FACE_LIPOSUCTION', 3, 'SURGERY', '풀페이스', 'HS_FACE_LIPOSUCTION_FULL_FACE', '지방흡입 / 이식 > 얼굴지방흡입 > 풀페이스', 1),
('HOSPITAL_MEDICAL', 'HS_FACE_LIPOSUCTION', 3, 'SURGERY', '볼', 'HS_FACE_LIPOSUCTION_CHEEK', '지방흡입 / 이식 > 얼굴지방흡입 > 볼', 2),
('HOSPITAL_MEDICAL', 'HS_FACE_LIPOSUCTION', 3, 'SURGERY', '턱', 'HS_FACE_LIPOSUCTION_CHIN', '지방흡입 / 이식 > 얼굴지방흡입 > 턱', 3),
('HOSPITAL_MEDICAL', 'HS_BODY', 2, 'SURGERY', '바디지방이식', 'HS_BODY_FAT_GRAFT', '지방흡입 / 이식 > 바디지방이식', 4),
('HOSPITAL_MEDICAL', 'HS_BODY_FAT_GRAFT', 3, 'SURGERY', '가슴', 'HS_BODY_FAT_GRAFT_BREAST', '지방흡입 / 이식 > 바디지방이식 > 가슴', 1),
('HOSPITAL_MEDICAL', 'HS_BODY_FAT_GRAFT', 3, 'SURGERY', '엉덩이 / 골반', 'HS_BODY_FAT_GRAFT_HIP_PELVIS', '지방흡입 / 이식 > 바디지방이식 > 엉덩이 / 골반', 2),
('HOSPITAL_MEDICAL', 'HS_BODY_FAT_GRAFT', 3, 'SURGERY', '기타', 'HS_BODY_FAT_GRAFT_OTHER', '지방흡입 / 이식 > 바디지방이식 > 기타', 3),
('HOSPITAL_MEDICAL', 'HS_BODY', 2, 'SURGERY', '얼굴지방이식', 'HS_FACE_FAT_GRAFT', '지방흡입 / 이식 > 얼굴지방이식', 5),
('HOSPITAL_MEDICAL', 'HS_FACE_FAT_GRAFT', 3, 'SURGERY', '풀페이스', 'HS_FACE_FAT_GRAFT_FULL_FACE', '지방흡입 / 이식 > 얼굴지방이식 > 풀페이스', 1),
('HOSPITAL_MEDICAL', 'HS_FACE_FAT_GRAFT', 3, 'SURGERY', '이마', 'HS_FACE_FAT_GRAFT_FOREHEAD', '지방흡입 / 이식 > 얼굴지방이식 > 이마', 2),
('HOSPITAL_MEDICAL', 'HS_FACE_FAT_GRAFT', 3, 'SURGERY', '볼', 'HS_FACE_FAT_GRAFT_CHEEK', '지방흡입 / 이식 > 얼굴지방이식 > 볼', 3),
('HOSPITAL_MEDICAL', 'HS_FACE_FAT_GRAFT', 3, 'SURGERY', '눈', 'HS_FACE_FAT_GRAFT_EYE', '지방흡입 / 이식 > 얼굴지방이식 > 눈', 4),
('HOSPITAL_MEDICAL', 'HS_FACE_FAT_GRAFT', 3, 'SURGERY', '기타 (턱, 광대, 관자, 팔자 등)', 'HS_FACE_FAT_GRAFT_OTHER', '지방흡입 / 이식 > 얼굴지방이식 > 기타 (턱, 광대, 관자, 팔자 등)', 5),
('HOSPITAL_MEDICAL', NULL, 1, 'SURGERY', '가슴', 'HS_BREAST', '가슴', 4),
('HOSPITAL_MEDICAL', 'HS_BREAST', 2, 'SURGERY', '가슴모양교정', 'HS_BREAST_SHAPE', '가슴 > 가슴모양교정', 1),
('HOSPITAL_MEDICAL', 'HS_BREAST_SHAPE', 3, 'SURGERY', '가슴확대(보형물)', 'HS_BREAST_SHAPE_IMPLANT_AUGMENTATION', '가슴 > 가슴모양교정 > 가슴확대(보형물)', 1),
('HOSPITAL_MEDICAL', 'HS_BREAST_SHAPE', 3, 'SURGERY', '가슴축소', 'HS_BREAST_SHAPE_REDUCTION', '가슴 > 가슴모양교정 > 가슴축소', 2),
('HOSPITAL_MEDICAL', 'HS_BREAST_SHAPE', 3, 'SURGERY', '부유방제거', 'HS_BREAST_SHAPE_ACCESSORY_REMOVAL', '가슴 > 가슴모양교정 > 부유방제거', 3),
('HOSPITAL_MEDICAL', 'HS_BREAST_SHAPE', 3, 'SURGERY', '기타(보형물제거, 이물질제거, 여유증, 흉터 등)', 'HS_BREAST_SHAPE_OTHER', '가슴 > 가슴모양교정 > 기타(보형물제거, 이물질제거, 여유증, 흉터 등)', 4),
('HOSPITAL_MEDICAL', 'HS_BREAST', 2, 'SURGERY', '유두 / 유륜', 'HS_BREAST_NIPPLE_AREOLA', '가슴 > 유두 / 유륜', 2),
('HOSPITAL_MEDICAL', 'HS_BREAST_NIPPLE_AREOLA', 3, 'SURGERY', '함몰유두', 'HS_BREAST_NIPPLE_INVERTED', '가슴 > 유두 / 유륜 > 함몰유두', 1),
('HOSPITAL_MEDICAL', 'HS_BREAST_NIPPLE_AREOLA', 3, 'SURGERY', '유두 / 유륜축소', 'HS_BREAST_NIPPLE_AREOLA_REDUCTION', '가슴 > 유두 / 유륜 > 유두 / 유륜축소', 2),
('HOSPITAL_MEDICAL', 'HS_BREAST', 2, 'SURGERY', '가슴재수술', 'HS_BREAST_REVISION', '가슴 > 가슴재수술', 3),
('HOSPITAL_MEDICAL', 'HS_BREAST_REVISION', 3, 'SURGERY', '가슴모양교정', 'HS_BREAST_REVISION_SHAPE', '가슴 > 가슴재수술 > 가슴모양교정', 1),
('HOSPITAL_MEDICAL', 'HS_BREAST_REVISION', 3, 'SURGERY', '유두 / 유륜', 'HS_BREAST_REVISION_NIPPLE_AREOLA', '가슴 > 가슴재수술 > 유두 / 유륜', 2),
('HOSPITAL_MEDICAL', 'HS_BREAST_REVISION', 3, 'SURGERY', '기타', 'HS_BREAST_REVISION_OTHER', '가슴 > 가슴재수술 > 기타', 3),
('HOSPITAL_MEDICAL', NULL, 1, 'SURGERY', '거상', 'HS_LIFT', '거상', 5),
('HOSPITAL_MEDICAL', 'HS_LIFT', 2, 'SURGERY', '얼굴거상', 'HS_LIFT_FACE', '거상 > 얼굴거상', 1),
('HOSPITAL_MEDICAL', 'HS_LIFT_FACE', 3, 'SURGERY', '안면거상', 'HS_LIFT_FACE_FULL', '거상 > 얼굴거상 > 안면거상', 1),
('HOSPITAL_MEDICAL', 'HS_LIFT_FACE', 3, 'SURGERY', '미니거상', 'HS_LIFT_FACE_MINI', '거상 > 얼굴거상 > 미니거상', 2),
('HOSPITAL_MEDICAL', 'HS_LIFT_FACE', 3, 'SURGERY', '이마거상', 'HS_LIFT_FOREHEAD', '거상 > 얼굴거상 > 이마거상', 3),
('HOSPITAL_MEDICAL', 'HS_LIFT_FACE', 3, 'SURGERY', '이마축소', 'HS_LIFT_FOREHEAD_REDUCTION', '거상 > 얼굴거상 > 이마축소', 4),
('HOSPITAL_MEDICAL', 'HS_LIFT_FACE', 3, 'SURGERY', '목거상', 'HS_LIFT_NECK', '거상 > 얼굴거상 > 목거상', 5),
('HOSPITAL_MEDICAL', 'HS_LIFT', 2, 'SURGERY', '바디거상', 'HS_LIFT_BODY', '거상 > 바디거상', 2),
('HOSPITAL_MEDICAL', 'HS_LIFT_BODY', 3, 'SURGERY', '가슴거상', 'HS_LIFT_BODY_BREAST', '거상 > 바디거상 > 가슴거상', 1),
('HOSPITAL_MEDICAL', 'HS_LIFT_BODY', 3, 'SURGERY', '복부거상', 'HS_LIFT_BODY_ABDOMEN', '거상 > 바디거상 > 복부거상', 2),
('HOSPITAL_MEDICAL', 'HS_LIFT_BODY', 3, 'SURGERY', '팔거상', 'HS_LIFT_BODY_ARM', '거상 > 바디거상 > 팔거상', 3),
('HOSPITAL_MEDICAL', 'HS_LIFT_BODY', 3, 'SURGERY', '기타', 'HS_LIFT_BODY_OTHER', '거상 > 바디거상 > 기타', 4),
('HOSPITAL_MEDICAL', 'HS_LIFT', 2, 'SURGERY', '거상재수술', 'HS_LIFT_REVISION', '거상 > 거상재수술', 3),
('HOSPITAL_MEDICAL', 'HS_LIFT_REVISION', 3, 'SURGERY', '가슴모양교정', 'HS_LIFT_REVISION_BREAST_SHAPE', '거상 > 거상재수술 > 가슴모양교정', 1),
('HOSPITAL_MEDICAL', 'HS_LIFT_REVISION', 3, 'SURGERY', '유두/유륜', 'HS_LIFT_REVISION_NIPPLE_AREOLA', '거상 > 거상재수술 > 유두/유륜', 2),
('HOSPITAL_MEDICAL', 'HS_LIFT_REVISION', 3, 'SURGERY', '기타', 'HS_LIFT_REVISION_OTHER', '거상 > 거상재수술 > 기타', 3),
('HOSPITAL_MEDICAL', NULL, 1, 'SURGERY', '안면윤곽 / 양악', 'HS_FACE_CONTOUR', '안면윤곽 / 양악', 6),
('HOSPITAL_MEDICAL', 'HS_FACE_CONTOUR', 2, 'SURGERY', '광대', 'HS_FACE_CONTOUR_CHEEKBONE', '안면윤곽 / 양악 > 광대', 1),
('HOSPITAL_MEDICAL', 'HS_FACE_CONTOUR_CHEEKBONE', 3, 'SURGERY', '광대축소', 'HS_FACE_CONTOUR_CHEEKBONE_REDUCTION', '안면윤곽 / 양악 > 광대 > 광대축소', 1),
('HOSPITAL_MEDICAL', 'HS_FACE_CONTOUR_CHEEKBONE', 3, 'SURGERY', '광대확대', 'HS_FACE_CONTOUR_CHEEKBONE_AUGMENTATION', '안면윤곽 / 양악 > 광대 > 광대확대', 2),
('HOSPITAL_MEDICAL', 'HS_FACE_CONTOUR', 2, 'SURGERY', '턱', 'HS_FACE_CONTOUR_JAW', '안면윤곽 / 양악 > 턱', 2),
('HOSPITAL_MEDICAL', 'HS_FACE_CONTOUR_JAW', 3, 'SURGERY', '사각턱', 'HS_FACE_CONTOUR_SQUARE_JAW', '안면윤곽 / 양악 > 턱 > 사각턱', 1),
('HOSPITAL_MEDICAL', 'HS_FACE_CONTOUR_JAW', 3, 'SURGERY', '턱끝', 'HS_FACE_CONTOUR_CHIN', '안면윤곽 / 양악 > 턱 > 턱끝', 2),
('HOSPITAL_MEDICAL', 'HS_FACE_CONTOUR', 2, 'SURGERY', '양악', 'HS_FACE_CONTOUR_DOUBLE_JAW', '안면윤곽 / 양악 > 양악', 3),
('HOSPITAL_MEDICAL', 'HS_FACE_CONTOUR_DOUBLE_JAW', 3, 'SURGERY', '양악', 'HS_FACE_CONTOUR_DOUBLE_JAW_BASIC', '안면윤곽 / 양악 > 양악 > 양악', 1),
('HOSPITAL_MEDICAL', 'HS_FACE_CONTOUR_DOUBLE_JAW', 3, 'SURGERY', '상악', 'HS_FACE_CONTOUR_UPPER_JAW', '안면윤곽 / 양악 > 양악 > 상악', 2),
('HOSPITAL_MEDICAL', 'HS_FACE_CONTOUR_DOUBLE_JAW', 3, 'SURGERY', '하악', 'HS_FACE_CONTOUR_LOWER_JAW', '안면윤곽 / 양악 > 양악 > 하악', 3),
('HOSPITAL_MEDICAL', 'HS_FACE_CONTOUR', 2, 'SURGERY', '안면윤곽재수술', 'HS_FACE_CONTOUR_REVISION', '안면윤곽 / 양악 > 안면윤곽재수술', 4),
('HOSPITAL_MEDICAL', 'HS_FACE_CONTOUR_REVISION', 3, 'SURGERY', '광대', 'HS_FACE_CONTOUR_REVISION_CHEEKBONE', '안면윤곽 / 양악 > 안면윤곽재수술 > 광대', 1),
('HOSPITAL_MEDICAL', 'HS_FACE_CONTOUR_REVISION', 3, 'SURGERY', '윤곽', 'HS_FACE_CONTOUR_REVISION_CONTOUR', '안면윤곽 / 양악 > 안면윤곽재수술 > 윤곽', 2),
('HOSPITAL_MEDICAL', 'HS_FACE_CONTOUR_REVISION', 3, 'SURGERY', '양악', 'HS_FACE_CONTOUR_REVISION_DOUBLE_JAW', '안면윤곽 / 양악 > 안면윤곽재수술 > 양악', 3),
('HOSPITAL_MEDICAL', NULL, 1, 'SURGERY', '모발이식', 'HS_HAIR_TRANSPLANT', '모발이식', 7),
('HOSPITAL_MEDICAL', 'HS_HAIR_TRANSPLANT', 2, 'SURGERY', '절개', 'HS_HAIR_TRANSPLANT_INCISION', '모발이식 > 절개', 1),
('HOSPITAL_MEDICAL', 'HS_HAIR_TRANSPLANT', 2, 'SURGERY', '비절개', 'HS_HAIR_TRANSPLANT_NON_INCISION', '모발이식 > 비절개', 2),
('HOSPITAL_MEDICAL', NULL, 1, 'SURGERY', '기타', 'HS_SURGERY_OTHER', '기타', 8),
('HOSPITAL_MEDICAL', 'HS_SURGERY_OTHER', 2, 'SURGERY', '입술성형', 'HS_SURGERY_OTHER_LIP', '기타 > 입술성형', 1),
('HOSPITAL_MEDICAL', 'HS_SURGERY_OTHER_LIP', 3, 'SURGERY', '입꼬리', 'HS_SURGERY_OTHER_LIP_CORNER', '기타 > 입술성형 > 입꼬리', 1),
('HOSPITAL_MEDICAL', 'HS_SURGERY_OTHER_LIP', 3, 'SURGERY', '입술축소', 'HS_SURGERY_OTHER_LIP_REDUCTION', '기타 > 입술성형 > 입술축소', 2),
('HOSPITAL_MEDICAL', 'HS_SURGERY_OTHER', 2, 'SURGERY', '보조개성형', 'HS_SURGERY_OTHER_DIMPLE', '기타 > 보조개성형', 2),
('HOSPITAL_MEDICAL', 'HS_SURGERY_OTHER', 2, 'SURGERY', '귀성형', 'HS_SURGERY_OTHER_EAR', '기타 > 귀성형', 3),
('HOSPITAL_MEDICAL', 'HS_SURGERY_OTHER', 2, 'SURGERY', '보형물', 'HS_SURGERY_OTHER_IMPLANT', '기타 > 보형물', 4),
('HOSPITAL_MEDICAL', 'HS_SURGERY_OTHER_IMPLANT', 3, 'SURGERY', '이마', 'HS_SURGERY_OTHER_IMPLANT_FOREHEAD', '기타 > 보형물 > 이마', 1),
('HOSPITAL_MEDICAL', 'HS_SURGERY_OTHER_IMPLANT', 3, 'SURGERY', '턱', 'HS_SURGERY_OTHER_IMPLANT_CHIN', '기타 > 보형물 > 턱', 2),
('HOSPITAL_MEDICAL', 'HS_SURGERY_OTHER_IMPLANT', 3, 'SURGERY', '팔자', 'HS_SURGERY_OTHER_IMPLANT_NASOLABIAL', '기타 > 보형물 > 팔자', 3),
('HOSPITAL_MEDICAL', 'HS_SURGERY_OTHER', 2, 'SURGERY', '기타성형', 'HS_SURGERY_OTHER_ETC', '기타 > 기타성형', 5),
('HOSPITAL_MEDICAL', NULL, 1, 'TREATMENT', '리프팅', 'HT_LIFTING', '리프팅', 9),
('HOSPITAL_MEDICAL', 'HT_LIFTING', 2, 'TREATMENT', '레이저리프팅', 'HT_LIFTING_LASER', '리프팅 > 레이저리프팅', 1),
('HOSPITAL_MEDICAL', 'HT_LIFTING', 2, 'TREATMENT', '실리프팅', 'HT_LIFTING_THREAD', '리프팅 > 실리프팅', 2),
('HOSPITAL_MEDICAL', 'HT_LIFTING', 2, 'TREATMENT', '그외 (코 / 신경차단)', 'HT_LIFTING_OTHER', '리프팅 > 그외 (코 / 신경차단)', 3),
('HOSPITAL_MEDICAL', NULL, 1, 'TREATMENT', '필러', 'HT_FILLER', '필러', 10),
('HOSPITAL_MEDICAL', 'HT_FILLER', 2, 'TREATMENT', '풀페이스', 'HT_FILLER_FULL_FACE', '필러 > 풀페이스', 1),
('HOSPITAL_MEDICAL', 'HT_FILLER', 2, 'TREATMENT', '이마', 'HT_FILLER_FOREHEAD', '필러 > 이마', 2),
('HOSPITAL_MEDICAL', 'HT_FILLER', 2, 'TREATMENT', '코', 'HT_FILLER_NOSE', '필러 > 코', 3),
('HOSPITAL_MEDICAL', 'HT_FILLER', 2, 'TREATMENT', '입술', 'HT_FILLER_LIP', '필러 > 입술', 4),
('HOSPITAL_MEDICAL', 'HT_FILLER', 2, 'TREATMENT', '앞턱', 'HT_FILLER_CHIN', '필러 > 앞턱', 5),
('HOSPITAL_MEDICAL', 'HT_FILLER', 2, 'TREATMENT', '팔자', 'HT_FILLER_NASOLABIAL', '필러 > 팔자', 6),
('HOSPITAL_MEDICAL', 'HT_FILLER', 2, 'TREATMENT', '엉덩이/골반', 'HT_FILLER_HIP_PELVIS', '필러 > 엉덩이/골반', 7),
('HOSPITAL_MEDICAL', 'HT_FILLER', 2, 'TREATMENT', '가슴', 'HT_FILLER_BREAST', '필러 > 가슴', 8),
('HOSPITAL_MEDICAL', 'HT_FILLER', 2, 'TREATMENT', '어깨', 'HT_FILLER_SHOULDER', '필러 > 어깨', 9),
('HOSPITAL_MEDICAL', 'HT_FILLER', 2, 'TREATMENT', '필러제거', 'HT_FILLER_REMOVAL', '필러 > 필러제거', 10),
('HOSPITAL_MEDICAL', 'HT_FILLER', 2, 'TREATMENT', '기타 (눈/미간/관자놀이/볼/광대/목/귀/종아리)', 'HT_FILLER_OTHER', '필러 > 기타 (눈/미간/관자놀이/볼/광대/목/귀/종아리)', 11),
('HOSPITAL_MEDICAL', NULL, 1, 'TREATMENT', '보톡스', 'HT_BOTOX', '보톡스', 11),
('HOSPITAL_MEDICAL', 'HT_BOTOX', 2, 'TREATMENT', '풀페이스', 'HT_BOTOX_FULL_FACE', '보톡스 > 풀페이스', 1),
('HOSPITAL_MEDICAL', 'HT_BOTOX', 2, 'TREATMENT', '턱', 'HT_BOTOX_JAW', '보톡스 > 턱', 2),
('HOSPITAL_MEDICAL', 'HT_BOTOX', 2, 'TREATMENT', '침샘', 'HT_BOTOX_SALIVARY', '보톡스 > 침샘', 3),
('HOSPITAL_MEDICAL', 'HT_BOTOX', 2, 'TREATMENT', '이마', 'HT_BOTOX_FOREHEAD', '보톡스 > 이마', 4),
('HOSPITAL_MEDICAL', 'HT_BOTOX', 2, 'TREATMENT', '미간', 'HT_BOTOX_GLABELLA', '보톡스 > 미간', 5),
('HOSPITAL_MEDICAL', 'HT_BOTOX', 2, 'TREATMENT', '눈가', 'HT_BOTOX_EYE', '보톡스 > 눈가', 6),
('HOSPITAL_MEDICAL', 'HT_BOTOX', 2, 'TREATMENT', '입꼬리', 'HT_BOTOX_MOUTH_CORNER', '보톡스 > 입꼬리', 7),
('HOSPITAL_MEDICAL', 'HT_BOTOX', 2, 'TREATMENT', '스킨', 'HT_BOTOX_SKIN', '보톡스 > 스킨', 8),
('HOSPITAL_MEDICAL', 'HT_BOTOX', 2, 'TREATMENT', '승모근/쇄골', 'HT_BOTOX_TRAP_CLAVICLE', '보톡스 > 승모근/쇄골', 9),
('HOSPITAL_MEDICAL', 'HT_BOTOX', 2, 'TREATMENT', '기타 (잇몸/다한증/볼/광대/코/목/팔자/관자놀이/종아리/허벅지/팔)', 'HT_BOTOX_OTHER', '보톡스 > 기타 (잇몸/다한증/볼/광대/코/목/팔자/관자놀이/종아리/허벅지/팔)', 10),
('HOSPITAL_MEDICAL', NULL, 1, 'TREATMENT', '지방분해주사', 'HT_FAT_DISSOLVING_INJECTION', '지방분해주사', 12),
('HOSPITAL_MEDICAL', 'HT_FAT_DISSOLVING_INJECTION', 2, 'TREATMENT', '풀페이스', 'HT_FAT_DISSOLVING_FULL_FACE', '지방분해주사 > 풀페이스', 1),
('HOSPITAL_MEDICAL', 'HT_FAT_DISSOLVING_INJECTION', 2, 'TREATMENT', '볼/광대', 'HT_FAT_DISSOLVING_CHEEK_CHEEKBONE', '지방분해주사 > 볼/광대', 2),
('HOSPITAL_MEDICAL', 'HT_FAT_DISSOLVING_INJECTION', 2, 'TREATMENT', '턱', 'HT_FAT_DISSOLVING_CHIN', '지방분해주사 > 턱', 3),
('HOSPITAL_MEDICAL', 'HT_FAT_DISSOLVING_INJECTION', 2, 'TREATMENT', '복부', 'HT_FAT_DISSOLVING_ABDOMEN', '지방분해주사 > 복부', 4),
('HOSPITAL_MEDICAL', 'HT_FAT_DISSOLVING_INJECTION', 2, 'TREATMENT', '팔', 'HT_FAT_DISSOLVING_ARM', '지방분해주사 > 팔', 5),
('HOSPITAL_MEDICAL', 'HT_FAT_DISSOLVING_INJECTION', 2, 'TREATMENT', '허벅지', 'HT_FAT_DISSOLVING_THIGH', '지방분해주사 > 허벅지', 6),
('HOSPITAL_MEDICAL', 'HT_FAT_DISSOLVING_INJECTION', 2, 'TREATMENT', '엉덩이', 'HT_FAT_DISSOLVING_HIP', '지방분해주사 > 엉덩이', 7),
('HOSPITAL_MEDICAL', 'HT_FAT_DISSOLVING_INJECTION', 2, 'TREATMENT', '기타 (무릎/종아리/발목/승모근/쇄골 등)', 'HT_FAT_DISSOLVING_OTHER', '지방분해주사 > 기타 (무릎/종아리/발목/승모근/쇄골 등)', 8),
('HOSPITAL_MEDICAL', NULL, 1, 'TREATMENT', '피부', 'HT_SKIN', '피부', 13),
('HOSPITAL_MEDICAL', 'HT_SKIN', 2, 'TREATMENT', '탄력/재생', 'HT_SKIN_ELASTIC_REGEN', '피부 > 탄력/재생', 1),
('HOSPITAL_MEDICAL', 'HT_SKIN_ELASTIC_REGEN', 3, 'TREATMENT', '스킨부스터', 'HT_SKIN_ELASTIC_REGEN_SKINBOOSTER', '피부 > 탄력/재생 > 스킨부스터', 1),
('HOSPITAL_MEDICAL', 'HT_SKIN_ELASTIC_REGEN', 3, 'TREATMENT', '콜라겐부스터', 'HT_SKIN_ELASTIC_REGEN_COLLAGEN', '피부 > 탄력/재생 > 콜라겐부스터', 2),
('HOSPITAL_MEDICAL', 'HT_SKIN_ELASTIC_REGEN', 3, 'TREATMENT', '비타민주사/수액', 'HT_SKIN_ELASTIC_REGEN_VITAMIN', '피부 > 탄력/재생 > 비타민주사/수액', 3),
('HOSPITAL_MEDICAL', 'HT_SKIN_ELASTIC_REGEN', 3, 'TREATMENT', '스킨케어', 'HT_SKIN_ELASTIC_REGEN_SKINCARE', '피부 > 탄력/재생 > 스킨케어', 4),
('HOSPITAL_MEDICAL', 'HT_SKIN', 2, 'TREATMENT', '미백/잡티/홍조', 'HT_SKIN_WHITENING_REDNESS', '피부 > 미백/잡티/홍조', 2),
('HOSPITAL_MEDICAL', 'HT_SKIN_WHITENING_REDNESS', 3, 'TREATMENT', '기미/잡티/주근깨', 'HT_SKIN_WHITENING_BLEMISH', '피부 > 미백/잡티/홍조 > 기미/잡티/주근깨', 1),
('HOSPITAL_MEDICAL', 'HT_SKIN_WHITENING_REDNESS', 3, 'TREATMENT', '점/검버섯', 'HT_SKIN_WHITENING_MOLE_SPOT', '피부 > 미백/잡티/홍조 > 점/검버섯', 2),
('HOSPITAL_MEDICAL', 'HT_SKIN_WHITENING_REDNESS', 3, 'TREATMENT', '피부톤업', 'HT_SKIN_WHITENING_TONE_UP', '피부 > 미백/잡티/홍조 > 피부톤업', 3),
('HOSPITAL_MEDICAL', 'HT_SKIN_WHITENING_REDNESS', 3, 'TREATMENT', '다크서클', 'HT_SKIN_WHITENING_DARK_CIRCLE', '피부 > 미백/잡티/홍조 > 다크서클', 4),
('HOSPITAL_MEDICAL', 'HT_SKIN_WHITENING_REDNESS', 3, 'TREATMENT', '홍조', 'HT_SKIN_WHITENING_REDNESS_BASIC', '피부 > 미백/잡티/홍조 > 홍조', 5),
('HOSPITAL_MEDICAL', 'HT_SKIN_WHITENING_REDNESS', 3, 'TREATMENT', '스킨케어', 'HT_SKIN_WHITENING_SKINCARE', '피부 > 미백/잡티/홍조 > 스킨케어', 6),
('HOSPITAL_MEDICAL', 'HT_SKIN_WHITENING_REDNESS', 3, 'TREATMENT', '바디미백 (겨드랑이/팔꿈치/Y존/엉덩이/무릎/발꿈치/복숭아뼈/유두/유륜)', 'HT_SKIN_WHITENING_BODY', '피부 > 미백/잡티/홍조 > 바디미백 (겨드랑이/팔꿈치/Y존/엉덩이/무릎/발꿈치/복숭아뼈/유두/유륜)', 7),
('HOSPITAL_MEDICAL', 'HT_SKIN_WHITENING_REDNESS', 3, 'TREATMENT', '튼살치료 (레이저, 마이크로니들)', 'HT_SKIN_WHITENING_STRETCH_MARK', '피부 > 미백/잡티/홍조 > 튼살치료 (레이저, 마이크로니들)', 8),
('HOSPITAL_MEDICAL', 'HT_SKIN', 2, 'TREATMENT', '보습/진정', 'HT_SKIN_MOISTURE_SOOTHING', '피부 > 보습/진정', 3),
('HOSPITAL_MEDICAL', 'HT_SKIN_MOISTURE_SOOTHING', 3, 'TREATMENT', '스킨부스터', 'HT_SKIN_MOISTURE_SKINBOOSTER', '피부 > 보습/진정 > 스킨부스터', 1),
('HOSPITAL_MEDICAL', 'HT_SKIN_MOISTURE_SOOTHING', 3, 'TREATMENT', '비타민주사/수액', 'HT_SKIN_MOISTURE_VITAMIN', '피부 > 보습/진정 > 비타민주사/수액', 2),
('HOSPITAL_MEDICAL', 'HT_SKIN_MOISTURE_SOOTHING', 3, 'TREATMENT', '스킨케어', 'HT_SKIN_MOISTURE_SKINCARE', '피부 > 보습/진정 > 스킨케어', 3),
('HOSPITAL_MEDICAL', 'HT_SKIN', 2, 'TREATMENT', '여드름/모공', 'HT_SKIN_ACNE_PORE', '피부 > 여드름/모공', 4),
('HOSPITAL_MEDICAL', 'HT_SKIN_ACNE_PORE', 3, 'TREATMENT', '모공케어', 'HT_SKIN_ACNE_PORE_CARE', '피부 > 여드름/모공 > 모공케어', 1),
('HOSPITAL_MEDICAL', 'HT_SKIN_ACNE_PORE', 3, 'TREATMENT', '여드름압출', 'HT_SKIN_ACNE_EXTRACTION', '피부 > 여드름/모공 > 여드름압출', 2),
('HOSPITAL_MEDICAL', 'HT_SKIN_ACNE_PORE', 3, 'TREATMENT', '여드름흉터', 'HT_SKIN_ACNE_SCAR', '피부 > 여드름/모공 > 여드름흉터', 3),
('HOSPITAL_MEDICAL', 'HT_SKIN_ACNE_PORE', 3, 'TREATMENT', '여드름염증', 'HT_SKIN_ACNE_INFLAMMATION', '피부 > 여드름/모공 > 여드름염증', 4),
('HOSPITAL_MEDICAL', 'HT_SKIN_ACNE_PORE', 3, 'TREATMENT', '스킨케어', 'HT_SKIN_ACNE_SKINCARE', '피부 > 여드름/모공 > 스킨케어', 5),
('HOSPITAL_MEDICAL', 'HT_SKIN', 2, 'TREATMENT', '피부질환', 'HT_SKIN_DISEASE', '피부 > 피부질환', 5),
('HOSPITAL_MEDICAL', 'HT_SKIN_DISEASE', 3, 'TREATMENT', '아토피', 'HT_SKIN_DISEASE_ATOPY', '피부 > 피부질환 > 아토피', 1),
('HOSPITAL_MEDICAL', 'HT_SKIN_DISEASE', 3, 'TREATMENT', '지루성피부염', 'HT_SKIN_DISEASE_SEBORRHEIC', '피부 > 피부질환 > 지루성피부염', 2),
('HOSPITAL_MEDICAL', 'HT_SKIN_DISEASE', 3, 'TREATMENT', '액취증/다한증', 'HT_SKIN_DISEASE_OSMIDROSIS_HYPERHIDROSIS', '피부 > 피부질환 > 액취증/다한증', 3),
('HOSPITAL_MEDICAL', 'HT_SKIN_DISEASE', 3, 'TREATMENT', '흉터/화상', 'HT_SKIN_DISEASE_SCAR_BURN', '피부 > 피부질환 > 흉터/화상', 4),
('HOSPITAL_MEDICAL', 'HT_SKIN_DISEASE', 3, 'TREATMENT', '사마귀/티눈', 'HT_SKIN_DISEASE_WART_CALLUS', '피부 > 피부질환 > 사마귀/티눈', 5),
('HOSPITAL_MEDICAL', 'HT_SKIN_DISEASE', 3, 'TREATMENT', '환관종/비립종/쥐젖', 'HT_SKIN_DISEASE_SYRINGOMA_MILIA_TAG', '피부 > 피부질환 > 환관종/비립종/쥐젖', 6),
('HOSPITAL_MEDICAL', 'HT_SKIN_DISEASE', 3, 'TREATMENT', '기타', 'HT_SKIN_DISEASE_OTHER', '피부 > 피부질환 > 기타', 7),
('HOSPITAL_MEDICAL', NULL, 1, 'TREATMENT', '제모/탈모', 'HT_HAIR_REMOVAL_LOSS', '제모/탈모', 14),
('HOSPITAL_MEDICAL', 'HT_HAIR_REMOVAL_LOSS', 2, 'TREATMENT', '제모', 'HT_HAIR_REMOVAL', '제모/탈모 > 제모', 1),
('HOSPITAL_MEDICAL', 'HT_HAIR_REMOVAL', 3, 'TREATMENT', '얼굴제모', 'HT_HAIR_REMOVAL_FACE', '제모/탈모 > 제모 > 얼굴제모', 1),
('HOSPITAL_MEDICAL', 'HT_HAIR_REMOVAL', 3, 'TREATMENT', '바디제모', 'HT_HAIR_REMOVAL_BODY', '제모/탈모 > 제모 > 바디제모', 2),
('HOSPITAL_MEDICAL', 'HT_HAIR_REMOVAL_LOSS', 2, 'TREATMENT', '탈모', 'HT_HAIR_LOSS', '제모/탈모 > 탈모', 2),
('HOSPITAL_MEDICAL', 'HT_HAIR_LOSS', 3, 'TREATMENT', '레이저', 'HT_HAIR_LOSS_LASER', '제모/탈모 > 탈모 > 레이저', 1),
('HOSPITAL_MEDICAL', 'HT_HAIR_LOSS', 3, 'TREATMENT', '약처방', 'HT_HAIR_LOSS_MEDICINE', '제모/탈모 > 탈모 > 약처방', 2),
('HOSPITAL_MEDICAL', 'HT_HAIR_LOSS', 3, 'TREATMENT', '기타', 'HT_HAIR_LOSS_OTHER', '제모/탈모 > 탈모 > 기타', 3),
('HOSPITAL_MEDICAL', 'HT_HAIR_REMOVAL_LOSS', 2, 'TREATMENT', '케어', 'HT_HAIR_CARE', '제모/탈모 > 케어', 3),
('HOSPITAL_MEDICAL', 'HT_HAIR_CARE', 3, 'TREATMENT', '두피케어', 'HT_HAIR_CARE_SCALP', '제모/탈모 > 케어 > 두피케어', 1),
('HOSPITAL_MEDICAL', 'HT_HAIR_CARE', 3, 'TREATMENT', '두피/모낭주사', 'HT_HAIR_CARE_SCALP_INJECTION', '제모/탈모 > 케어 > 두피/모낭주사', 2),
('HOSPITAL_MEDICAL', NULL, 1, 'TREATMENT', '치과', 'HT_DENTAL', '치과', 15),
('HOSPITAL_MEDICAL', 'HT_DENTAL', 2, 'TREATMENT', '치아교정', 'HT_DENTAL_ORTHODONTICS', '치과 > 치아교정', 1),
('HOSPITAL_MEDICAL', 'HT_DENTAL_ORTHODONTICS', 3, 'TREATMENT', '전체교정', 'HT_DENTAL_ORTHODONTICS_FULL', '치과 > 치아교정 > 전체교정', 1),
('HOSPITAL_MEDICAL', 'HT_DENTAL_ORTHODONTICS', 3, 'TREATMENT', '부분교정', 'HT_DENTAL_ORTHODONTICS_PARTIAL', '치과 > 치아교정 > 부분교정', 2),
('HOSPITAL_MEDICAL', 'HT_DENTAL', 2, 'TREATMENT', '치아미백', 'HT_DENTAL_WHITENING', '치과 > 치아미백', 2),
('HOSPITAL_MEDICAL', 'HT_DENTAL_WHITENING', 3, 'TREATMENT', '라미네이트', 'HT_DENTAL_WHITENING_LAMINATE', '치과 > 치아미백 > 라미네이트', 1),
('HOSPITAL_MEDICAL', 'HT_DENTAL_WHITENING', 3, 'TREATMENT', '올세라믹', 'HT_DENTAL_WHITENING_ALL_CERAMIC', '치과 > 치아미백 > 올세라믹', 2),
('HOSPITAL_MEDICAL', 'HT_DENTAL_WHITENING', 3, 'TREATMENT', '미백제도포', 'HT_DENTAL_WHITENING_AGENT', '치과 > 치아미백 > 미백제도포', 3),
('HOSPITAL_MEDICAL', 'HT_DENTAL_WHITENING', 3, 'TREATMENT', '미니쉬', 'HT_DENTAL_WHITENING_MINISH', '치과 > 치아미백 > 미니쉬', 4),
('HOSPITAL_MEDICAL', 'HT_DENTAL', 2, 'TREATMENT', '치아치료', 'HT_DENTAL_TREATMENT', '치과 > 치아치료', 3),
('HOSPITAL_MEDICAL', 'HT_DENTAL_TREATMENT', 3, 'TREATMENT', '임플란트', 'HT_DENTAL_TREATMENT_IMPLANT', '치과 > 치아치료 > 임플란트', 1),
('HOSPITAL_MEDICAL', 'HT_DENTAL_TREATMENT', 3, 'TREATMENT', '충치치료', 'HT_DENTAL_TREATMENT_CAVITY', '치과 > 치아치료 > 충치치료', 2),
('HOSPITAL_MEDICAL', 'HT_DENTAL_TREATMENT', 3, 'TREATMENT', '치아다듬기', 'HT_DENTAL_TREATMENT_TOOTH_CONTOURING', '치과 > 치아치료 > 치아다듬기', 3),
('HOSPITAL_MEDICAL', 'HT_DENTAL', 2, 'TREATMENT', '잇몸관리', 'HT_DENTAL_GUM', '치과 > 잇몸관리', 4),
('HOSPITAL_MEDICAL', 'HT_DENTAL_GUM', 3, 'TREATMENT', '잇몸라인', 'HT_DENTAL_GUM_LINE', '치과 > 잇몸관리 > 잇몸라인', 1),
('HOSPITAL_MEDICAL', NULL, 1, 'TREATMENT', '부인과', 'HT_GYNECOLOGY', '부인과', 16),
('HOSPITAL_MEDICAL', 'HT_GYNECOLOGY', 2, 'TREATMENT', '질필러', 'HT_GYNECOLOGY_VAGINAL_FILLER', '부인과 > 질필러', 1),
('HOSPITAL_MEDICAL', 'HT_GYNECOLOGY', 2, 'TREATMENT', '질레이저', 'HT_GYNECOLOGY_VAGINAL_LASER', '부인과 > 질레이저', 2),
('HOSPITAL_MEDICAL', 'HT_GYNECOLOGY', 2, 'TREATMENT', '그외', 'HT_GYNECOLOGY_OTHER', '부인과 > 그외', 3),
('HOSPITAL_MEDICAL', NULL, 1, 'TREATMENT', '안과', 'HT_OPHTHALMOLOGY', '안과', 17),
('HOSPITAL_MEDICAL', 'HT_OPHTHALMOLOGY', 2, 'TREATMENT', '라식/라섹', 'HT_OPHTHALMOLOGY_LASIK_LASEK', '안과 > 라식/라섹', 1),
('HOSPITAL_MEDICAL', 'HT_OPHTHALMOLOGY', 2, 'TREATMENT', '렌즈삽입', 'HT_OPHTHALMOLOGY_LENS_IMPLANT', '안과 > 렌즈삽입', 2),
('HOSPITAL_MEDICAL', 'HT_OPHTHALMOLOGY', 2, 'TREATMENT', '안구건조증', 'HT_OPHTHALMOLOGY_DRY_EYE', '안과 > 안구건조증', 3),
('HOSPITAL_MEDICAL', NULL, 1, 'TREATMENT', '한방', 'HT_ORIENTAL', '한방', 18),
('HOSPITAL_MEDICAL', 'HT_ORIENTAL', 2, 'TREATMENT', '다이어트', 'HT_ORIENTAL_DIET', '한방 > 다이어트', 1),
('HOSPITAL_MEDICAL', 'HT_ORIENTAL', 2, 'TREATMENT', '여드름/모공', 'HT_ORIENTAL_ACNE_PORE', '한방 > 여드름/모공', 2),
('HOSPITAL_MEDICAL', 'HT_ORIENTAL', 2, 'TREATMENT', '탄력/재생', 'HT_ORIENTAL_ELASTIC_REGEN', '한방 > 탄력/재생', 3),
('HOSPITAL_MEDICAL', 'HT_ORIENTAL', 2, 'TREATMENT', '미백/잡티/홍조', 'HT_ORIENTAL_WHITENING_REDNESS', '한방 > 미백/잡티/홍조', 4),
('HOSPITAL_MEDICAL', 'HT_ORIENTAL', 2, 'TREATMENT', '튼살치료', 'HT_ORIENTAL_STRETCH_MARK', '한방 > 튼살치료', 5);

INSERT IGNORE INTO categories (
    domain, parent_id, depth, group_code, name, code, full_path, sort_order, status, is_menu_visible
)
SELECT
    seed.domain,
    parent.id,
    seed.depth,
    seed.group_code,
    seed.name,
    seed.code,
    seed.full_path,
    seed.sort_order,
    'ACTIVE',
    TRUE
FROM category_seed seed
LEFT JOIN categories parent
    ON parent.domain = seed.domain
   AND parent.code = seed.parent_code
WHERE seed.depth = 1;

INSERT IGNORE INTO categories (
    domain, parent_id, depth, group_code, name, code, full_path, sort_order, status, is_menu_visible
)
SELECT
    seed.domain,
    parent.id,
    seed.depth,
    seed.group_code,
    seed.name,
    seed.code,
    seed.full_path,
    seed.sort_order,
    'ACTIVE',
    TRUE
FROM category_seed seed
LEFT JOIN categories parent
    ON parent.domain = seed.domain
   AND parent.code = seed.parent_code
WHERE seed.depth = 2;

INSERT IGNORE INTO categories (
    domain, parent_id, depth, group_code, name, code, full_path, sort_order, status, is_menu_visible
)
SELECT
    seed.domain,
    parent.id,
    seed.depth,
    seed.group_code,
    seed.name,
    seed.code,
    seed.full_path,
    seed.sort_order,
    'ACTIVE',
    TRUE
FROM category_seed seed
LEFT JOIN categories parent
    ON parent.domain = seed.domain
   AND parent.code = seed.parent_code
WHERE seed.depth = 3;

UPDATE categories category
JOIN category_seed seed
    ON seed.domain = category.domain
   AND seed.code = category.code
LEFT JOIN categories parent
    ON parent.domain = seed.domain
   AND parent.code = seed.parent_code
SET category.parent_id = parent.id,
    category.depth = seed.depth,
    category.group_code = seed.group_code,
    category.name = seed.name,
    category.full_path = seed.full_path,
    category.sort_order = seed.sort_order,
    category.status = 'ACTIVE',
    category.is_menu_visible = TRUE;

CREATE TEMPORARY TABLE category_usage_seed (
    `usage` VARCHAR(60) NOT NULL,
    category_code VARCHAR(80) NOT NULL,
    sort_order INT NOT NULL,
    PRIMARY KEY (`usage`, category_code)
);

INSERT INTO category_usage_seed (`usage`, category_code, sort_order) VALUES
('HOSPITAL_DOCTOR_SUBJECT', 'HS_EYE', 1),
('HOSPITAL_DOCTOR_SUBJECT', 'HS_NOSE', 2),
('HOSPITAL_DOCTOR_SUBJECT', 'HS_BODY', 3),
('HOSPITAL_DOCTOR_SUBJECT', 'HS_BREAST', 4),
('HOSPITAL_DOCTOR_SUBJECT', 'HS_LIFT', 5),
('HOSPITAL_DOCTOR_SUBJECT', 'HS_FACE_CONTOUR', 6),
('HOSPITAL_DOCTOR_SUBJECT', 'HS_HAIR_TRANSPLANT', 7),
('HOSPITAL_DOCTOR_SUBJECT', 'HS_SURGERY_OTHER', 8),
('HOSPITAL_DOCTOR_SUBJECT', 'HT_LIFTING', 9),
('HOSPITAL_DOCTOR_SUBJECT', 'HT_FILLER', 10),
('HOSPITAL_DOCTOR_SUBJECT', 'HT_BOTOX', 11),
('HOSPITAL_DOCTOR_SUBJECT', 'HT_FAT_DISSOLVING_INJECTION', 12),
('HOSPITAL_DOCTOR_SUBJECT', 'HT_SKIN', 13),
('HOSPITAL_DOCTOR_SUBJECT', 'HT_HAIR_REMOVAL_LOSS', 14),
('HOSPITAL_DOCTOR_SUBJECT', 'HT_DENTAL', 15),
('HOSPITAL_DOCTOR_SUBJECT', 'HT_GYNECOLOGY', 16),
('HOSPITAL_DOCTOR_SUBJECT', 'HT_OPHTHALMOLOGY', 17),
('HOSPITAL_DOCTOR_SUBJECT', 'HT_ORIENTAL', 18),
('HOSPITAL_REVIEW_SURGERY', 'HS_EYE', 1),
('HOSPITAL_REVIEW_SURGERY', 'HS_NOSE', 2),
('HOSPITAL_REVIEW_SURGERY', 'HS_BODY', 3),
('HOSPITAL_REVIEW_SURGERY', 'HS_BREAST', 4),
('HOSPITAL_REVIEW_SURGERY', 'HS_LIFT', 5),
('HOSPITAL_REVIEW_SURGERY', 'HS_FACE_CONTOUR', 6),
('HOSPITAL_REVIEW_SURGERY', 'HS_HAIR_TRANSPLANT', 7),
('HOSPITAL_REVIEW_SURGERY', 'HS_SURGERY_OTHER', 8),
('HOSPITAL_REVIEW_TREATMENT', 'HT_LIFTING', 1),
('HOSPITAL_REVIEW_TREATMENT', 'HT_FILLER', 2),
('HOSPITAL_REVIEW_TREATMENT', 'HT_BOTOX', 3),
('HOSPITAL_REVIEW_TREATMENT', 'HT_FAT_DISSOLVING_INJECTION', 4),
('HOSPITAL_REVIEW_TREATMENT', 'HT_SKIN', 5),
('HOSPITAL_REVIEW_TREATMENT', 'HT_HAIR_REMOVAL_LOSS', 6),
('HOSPITAL_REVIEW_TREATMENT', 'HT_DENTAL', 7),
('HOSPITAL_REVIEW_TREATMENT', 'HT_GYNECOLOGY', 8),
('HOSPITAL_REVIEW_TREATMENT', 'HT_OPHTHALMOLOGY', 9),
('HOSPITAL_REVIEW_TREATMENT', 'HT_ORIENTAL', 10),
('HOSPITAL_EVENT_SURGERY', 'HS_EYE', 1),
('HOSPITAL_EVENT_SURGERY', 'HS_NOSE', 2),
('HOSPITAL_EVENT_SURGERY', 'HS_BODY', 3),
('HOSPITAL_EVENT_SURGERY', 'HS_BREAST', 4),
('HOSPITAL_EVENT_SURGERY', 'HS_LIFT', 5),
('HOSPITAL_EVENT_SURGERY', 'HS_FACE_CONTOUR', 6),
('HOSPITAL_EVENT_SURGERY', 'HS_HAIR_TRANSPLANT', 7),
('HOSPITAL_EVENT_SURGERY', 'HS_SURGERY_OTHER', 8),
('HOSPITAL_EVENT_TREATMENT', 'HT_LIFTING', 1),
('HOSPITAL_EVENT_TREATMENT', 'HT_FILLER', 2),
('HOSPITAL_EVENT_TREATMENT', 'HT_BOTOX', 3),
('HOSPITAL_EVENT_TREATMENT', 'HT_FAT_DISSOLVING_INJECTION', 4),
('HOSPITAL_EVENT_TREATMENT', 'HT_SKIN', 5),
('HOSPITAL_EVENT_TREATMENT', 'HT_HAIR_REMOVAL_LOSS', 6),
('HOSPITAL_EVENT_TREATMENT', 'HT_DENTAL', 7),
('HOSPITAL_EVENT_TREATMENT', 'HT_GYNECOLOGY', 8),
('HOSPITAL_EVENT_TREATMENT', 'HT_OPHTHALMOLOGY', 9),
('HOSPITAL_EVENT_TREATMENT', 'HT_ORIENTAL', 10),
('HOSPITAL_VIDEO_CATEGORY', 'HS_EYE', 1),
('HOSPITAL_VIDEO_CATEGORY', 'HS_NOSE', 2),
('HOSPITAL_VIDEO_CATEGORY', 'HS_BODY', 3),
('HOSPITAL_VIDEO_CATEGORY', 'HS_BREAST', 4),
('HOSPITAL_VIDEO_CATEGORY', 'HS_LIFT', 5),
('HOSPITAL_VIDEO_CATEGORY', 'HS_FACE_CONTOUR', 6),
('HOSPITAL_VIDEO_CATEGORY', 'HS_HAIR_TRANSPLANT', 7),
('HOSPITAL_VIDEO_CATEGORY', 'HS_SURGERY_OTHER', 8),
('HOSPITAL_VIDEO_CATEGORY', 'HT_LIFTING', 9),
('HOSPITAL_VIDEO_CATEGORY', 'HT_FILLER', 10),
('HOSPITAL_VIDEO_CATEGORY', 'HT_BOTOX', 11),
('HOSPITAL_VIDEO_CATEGORY', 'HT_FAT_DISSOLVING_INJECTION', 12),
('HOSPITAL_VIDEO_CATEGORY', 'HT_SKIN', 13),
('HOSPITAL_VIDEO_CATEGORY', 'HT_HAIR_REMOVAL_LOSS', 14),
('HOSPITAL_VIDEO_CATEGORY', 'HT_DENTAL', 15),
('HOSPITAL_VIDEO_CATEGORY', 'HT_GYNECOLOGY', 16),
('HOSPITAL_VIDEO_CATEGORY', 'HT_OPHTHALMOLOGY', 17),
('HOSPITAL_VIDEO_CATEGORY', 'HT_ORIENTAL', 18),
('HOSPITAL_EVENT_AD_SURGERY', 'HS_EYE', 1),
('HOSPITAL_EVENT_AD_SURGERY', 'HS_NOSE', 2),
('HOSPITAL_EVENT_AD_SURGERY', 'HS_BODY', 3),
('HOSPITAL_EVENT_AD_SURGERY', 'HS_BREAST', 4),
('HOSPITAL_EVENT_AD_SURGERY', 'HS_LIFT', 5),
('HOSPITAL_EVENT_AD_SURGERY', 'HS_FACE_CONTOUR', 6),
('HOSPITAL_EVENT_AD_SURGERY', 'HS_HAIR_TRANSPLANT', 7),
('HOSPITAL_EVENT_AD_SURGERY', 'HS_SURGERY_OTHER', 8),
('HOSPITAL_EVENT_AD_TREATMENT', 'HT_LIFTING', 1),
('HOSPITAL_EVENT_AD_TREATMENT', 'HT_FILLER', 2),
('HOSPITAL_EVENT_AD_TREATMENT', 'HT_BOTOX', 3),
('HOSPITAL_EVENT_AD_TREATMENT', 'HT_FAT_DISSOLVING_INJECTION', 4),
('HOSPITAL_EVENT_AD_TREATMENT', 'HT_SKIN', 5),
('HOSPITAL_EVENT_AD_TREATMENT', 'HT_HAIR_REMOVAL_LOSS', 6),
('HOSPITAL_EVENT_AD_TREATMENT', 'HT_DENTAL', 7),
('HOSPITAL_EVENT_AD_TREATMENT', 'HT_GYNECOLOGY', 8),
('HOSPITAL_EVENT_AD_TREATMENT', 'HT_OPHTHALMOLOGY', 9),
('HOSPITAL_EVENT_AD_TREATMENT', 'HT_ORIENTAL', 10);

INSERT IGNORE INTO category_usages (`usage`, category_id, sort_order, status)
SELECT
    seed.`usage`,
    category.id,
    seed.sort_order,
    'ACTIVE'
FROM category_usage_seed seed
JOIN categories category
    ON category.domain = 'HOSPITAL_MEDICAL'
   AND category.code = seed.category_code
WHERE TRUE;

UPDATE category_usages category_usage
JOIN category_usage_seed seed
    ON seed.`usage` = category_usage.`usage`
JOIN categories category
    ON category.id = category_usage.category_id
   AND category.domain = 'HOSPITAL_MEDICAL'
   AND category.code = seed.category_code
SET category_usage.sort_order = seed.sort_order,
    category_usage.status = 'ACTIVE';

DROP TEMPORARY TABLE category_usage_seed;
DROP TEMPORARY TABLE category_seed;
