CREATE TABLE media (
    id BIGINT NOT NULL AUTO_INCREMENT,
    owner_type VARCHAR(50) NOT NULL,
    owner_id BIGINT NOT NULL,
    collection VARCHAR(50) NOT NULL,
    disk VARCHAR(20) NOT NULL DEFAULT 'LOCAL',
    path VARCHAR(512) NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    mime_type VARCHAR(127) NOT NULL,
    size BIGINT NOT NULL,
    width INT NULL,
    height INT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    metadata JSON NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    deleted_at TIMESTAMP(6) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY media_path_unique (path),
    INDEX media_owner_collection_order_idx (owner_type, owner_id, collection, deleted_at, sort_order, id),
    INDEX media_owner_deleted_idx (owner_type, owner_id, deleted_at, id),
    INDEX media_deleted_created_idx (deleted_at, created_at, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='폴리모픽 미디어 파일 메타데이터 테이블';
