CREATE TABLE partner_specialists (
    id BIGINT NOT NULL AUTO_INCREMENT,
    partner_id BIGINT NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    name VARCHAR(100) NOT NULL,
    gender VARCHAR(20) NOT NULL,
    position VARCHAR(50) NOT NULL,
    career_started_at DATE NULL,
    license_number VARCHAR(100) NULL,
    specialist_field VARCHAR(80) NOT NULL,
    educations JSON NULL,
    careers JSON NULL,
    etc_contents JSON NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'HIDDEN',
    allow_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    view_count BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    deleted_at TIMESTAMP(6) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY partner_specialists_license_number_unique (license_number),
    INDEX partner_specialists_partner_id_sort_order_index (partner_id, sort_order),
    INDEX partner_specialists_status_index (status),
    INDEX partner_specialists_allow_status_index (allow_status),
    INDEX partner_specialists_view_count_index (view_count),
    INDEX partner_specialists_specialist_field_index (specialist_field),
    INDEX h_specialists_deleted_id_idx (deleted_at, id),
    INDEX h_specialists_deleted_created_id_idx (deleted_at, created_at, id),
    INDEX h_specialists_deleted_partner_id_idx (deleted_at, partner_id, id),
    INDEX h_specialists_deleted_partner_sort_id_idx (deleted_at, partner_id, sort_order, id),
    INDEX h_specialists_deleted_allow_status_id_idx (deleted_at, allow_status, id),
    INDEX h_specialists_deleted_position_id_idx (deleted_at, position, id),
    INDEX h_specialists_deleted_specialist_id_idx (deleted_at, specialist_field, id),
    INDEX h_specialists_deleted_career_id_idx (deleted_at, career_started_at, id),
    CONSTRAINT fk_partner_specialists_partner
        FOREIGN KEY (partner_id) REFERENCES partners (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='파트너 소속 스페셜리스트 테이블';
