CREATE TABLE hospital_doctors (
    id BIGINT NOT NULL AUTO_INCREMENT,
    hospital_id BIGINT NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    name VARCHAR(100) NOT NULL,
    gender VARCHAR(20) NOT NULL,
    position VARCHAR(50) NOT NULL,
    career_started_at DATE NULL,
    license_number VARCHAR(100) NOT NULL,
    specialist_field VARCHAR(80) NOT NULL,
    educations JSON NULL,
    careers JSON NULL,
    etc_contents JSON NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'HIDDEN',
    allow_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    view_count BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    deleted_at TIMESTAMP(6) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY hospital_doctors_license_number_unique (license_number),
    INDEX hospital_doctors_hospital_id_sort_order_index (hospital_id, sort_order),
    INDEX hospital_doctors_status_index (status),
    INDEX hospital_doctors_allow_status_index (allow_status),
    INDEX hospital_doctors_view_count_index (view_count),
    INDEX hospital_doctors_specialist_field_index (specialist_field),
    INDEX h_doctors_deleted_id_idx (deleted_at, id),
    INDEX h_doctors_deleted_created_id_idx (deleted_at, created_at, id),
    INDEX h_doctors_deleted_hospital_id_idx (deleted_at, hospital_id, id),
    INDEX h_doctors_deleted_hospital_sort_id_idx (deleted_at, hospital_id, sort_order, id),
    INDEX h_doctors_deleted_allow_status_id_idx (deleted_at, allow_status, id),
    INDEX h_doctors_deleted_position_id_idx (deleted_at, position, id),
    INDEX h_doctors_deleted_specialist_id_idx (deleted_at, specialist_field, id),
    INDEX h_doctors_deleted_career_id_idx (deleted_at, career_started_at, id),
    CONSTRAINT fk_hospital_doctors_hospital
        FOREIGN KEY (hospital_id) REFERENCES hospitals (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='병원 소속 의료진 테이블';
